config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'home/feedback'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	layout 'resume'

  def index
  	@user = nil
  end

  def feedback
  	@feedback = Feedback.new(feedback_params)
  	if @feedback.save
  		flash[:notice] = 'Thanks For your feedback.'
  		redirect_to root_path
  	else
  		flash[:alert] = 'Feedback not submitted successfully'
  		redirect_to root_path
  	end
  end

  def create
    # @feedback = Feedback.new(feedback_params)

    # respond_to do |format|
    #   if @feedback.save
    #     format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
    #     format.json { render :show, status: :created, location: @feedback }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @feedback.errors, status: :unprocessable_entity }
    #   end
    # end	
  end

	def feedback_params
      params.require(:feedback).permit(:name, :contact, :email, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
	<div id="projects" class="portfolio">
		<div class="container">
			<h3 class="title wow zoomInLeft animated" data-wow-delay=".5s">My Projects & Certification</h3>
			<div class="sap_tabs">			
				<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
					<ul class="resp-tabs-list wow fadeInUp animated" data-wow-delay=".7s">
						<li class="resp-tab-item"><span>All</span></li>
						<li class="resp-tab-item"><span>Ruby On Rails </span></li>
						<li class="resp-tab-item"><span> Certification </span></li>
						<!-- <li class="resp-tab-item"><span>Wordpress</span></li>					 -->
					</ul>	
					<div class="clearfix"> </div>	
					<div class="resp-tabs-container">
						<div class="tab-1 resp-tab-content">
							<div class="tab_img">
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'project1.jpg' %>" class="swipebox" title="">
											<img src="<%= asset_path 'project1.jpg' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Project</span></h3>
												<p>Portico-admin application which manages the all the clients information.</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="col-md-4 portfolio-grids">
									<div class="grid effect-sarah">
										<a href="<%= asset_path 'certi1.jpg' %>" class="swipebox" title="">
											<img src="<%= asset_path 'certi1.jpg' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Certificate</span></h3>
												<p>JavaScript Certification course by Udemy.</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'project3.png' %>" class="swipebox" title="">
											<img src="<%= asset_path 'project3.png' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Project</span></h3>
													<p>StoolDuel which is a web application and api for gaming zone.</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'certi2.jpg' %>" class="swipebox" title="">
											<img src="<%= asset_path 'certi2.jpg' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Certificate</span></h3>
												<p>HTML and CSS certification online by Udemy</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'project2.png' %>" class="swipebox" title="">
											<img src="<%= asset_path 'project2.png' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Project</span></h3>
											<p>Aplus-shipping Management which manages the all the ecommerce orders for a stackholder at one place.</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'project4.png' %>" class="swipebox" title="">
											<img src="<%= asset_path 'project4.png' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Project</span></h3>
												<p>A service provider project which provide different services to clients.</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="clearfix"> </div>
							</div>
						</div>
						<div class="tab-1 resp-tab-content">
							<div class="tab_img">
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'project1.jpg' %>" class="swipebox" title="Portico-admin application which manages the all the clients information.">
											<img src="<%= asset_path 'project1.jpg' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Project</span></h3>
												<p>Portico-admin application which manages the all the clients information.</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'project2.png' %>" class="swipebox" title="Aplus-shipping Management which manages the all the ecommerce orders for a stackholder at one place.">
											<img src="<%= asset_path 'project2.png' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Project</span></h3>
												<p>Aplus-shipping Management which manages the all the ecommerce orders for a stackholder at one place.</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'project3.png' %>" class="swipebox" title="StoolDuel which is a web application and api for gaming zone.">
											<img src="<%= asset_path 'project3.png' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Project</span></h3>
												<p>StoolDuel which is a web application and api for gaming zone.</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'project4.png' %>" class="swipebox" title=">A service provider project which provide different services to clients.">
											<img src="<%= asset_path 'project4.png' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Project</span></h3>
												<p>A service provider project which provide different services to clients.</p>
											</div>
										</a>	
									</div>
								</div>								
								<div class="clearfix"> </div>
							</div>
						</div>
						<div class="tab-1 resp-tab-content">
							<div class="tab_img">
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'certi1.jpg' %>" class="swipebox" title="JavaScript Certification course by Udemy.">
											<img src="<%= asset_path 'certi1.jpg' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Certificate</span></h3>
												<p>JavaScript Certification course by Udemy.</p>
											</div>
										</a>	
									</div>
								</div>
								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%= asset_path 'certi2.jpg' %>" class="swipebox" title="HTML and CSS certification online by Udemy">
											<img src="<%= asset_path 'certi2.jpg' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Certificate</span></h3>
												<p>HTML and CSS certification online by Udemy</p>
											</div>
										</a>	
									</div>
								</div>
<!-- 								<div class="col-md-4 portfolio-grids">
									<div class="grid">
										<a href="<%#= asset_path 'g9.jpg' %>" class="swipebox" title="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis maximus tortor diam, ac lobortis justo rutrum quis. Praesent non purus fermentum, eleifend velit non">
											<img src="<%#= asset_path 'g9.jpg' %>" alt="" class="img-responsive" />
											<div class="figcaption">
												<h3>My<span> Project</span></h3>
												<p>Sarah likes to watch clouds. She's quite depressed.</p>
											</div>
										</a>	
									</div>
								</div> -->
								<div class="clearfix"> </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

<script src="../assets/easyResponsiveTabs.js" type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function () {
		$('#horizontalTab').easyResponsiveTabs({
			type: 'default', //Types: default, vertical, accordion           
			width: 'auto', //auto or any width like 600px
			fit: true   // 100% fit in a container
		});
	});		
</script>
<!--//ResponsiveTabs-->
<!-- swipe box js -->
<script src="../assets/jquery.swipebox.min.js"></script> 
	<script type="text/javascript">
		jQuery(function($) {
			$(".swipebox").swipebox();
		});
</script>

app/views/layouts/_normal_flash_messages.html.erb
<% if notice.present? %>
	<div class="alert alert-success alert-bordered alert-dismissible">
		<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
		<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
			<li><%= notice %></li>
		</ul>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-danger alert-bordered alert-dismissible">
		<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
		<ul class="list list-square mb-0">
			<li><%= alert %></li>
		</ul>
  </div>
<% end %>

app/views/layouts/_object_flash_messages.html.erb
<% if object.present? %>
	<% if object.errors.any? %>
		<% if object.errors.full_messages.present? %>
		  <div class="alert alert-danger alert-bordered alert-dismissible">
				<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
				<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
					<% object.errors.full_messages.each do |error_message| %>
						<li><%= error_message %></li>
					<% end %>
				</ul>
		  </div>
	  <% end %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AviResume</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/resume.html.erb
<!DOCTYPE html>
<!-- <html> -->
  <head>
    <title>AviResume</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link href='//fonts.googleapis.com/css?family=Overlock:400,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <!-- <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"> -->
    <script type="text/javascript">
      jQuery(document).ready(function($) {
        $(".scroll").click(function(event){   
          event.preventDefault();
          $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
        });
      });
    </script>
  </head>

  <body>
    <%= render "layouts/normal_flash_messages" %>
    <%= render 'layouts/resume/banner'%>
    <%= render 'layouts/resume/navigation'%>
    <%= render 'layouts/resume/about'%>
    <%= render 'layouts/resume/experience'%>
    <%= render 'layouts/resume/education'%>
    <%= render 'layouts/resume/skills'%>
    <%= yield %>
     <%= render 'layouts/resume/contact'%>
     <%= render 'layouts/resume/footer'%>
  </body>
  <script>
    $(".alert" ).fadeOut(6000);
    $(".notice" ).fadeOut(6000);
  </script>
</html>

app/views/layouts/resume/_about.html.erb
	<!--about-->
	<div id="about" class="about">
		<div class="container">
			<h3 class="title"> About Me</h3>
			<div class="col-md-8 about-left">
				<p>Innovative and committed Software Engineer with a passion for problem solving, code quality,debugging and designing solutions at any tier. Eager to take on challenging roles. Experience in full software development lifecycle from design, development to deployment. To work in learning and challenging environment, utilizing my skill and knowledge to be the best of my abilities and contribute positively to my personal growth as well as growth of the organization. 
				</p>
				<p>2+ years of experience professional IT experience in Software development of Application using Ruby on Rails.</p>
				<p>Special concentration in RoR application framework and Ruby language ,Experience in version control systems Github. Worked on client project using Ruby on rails, JavaScript and Ajax, Flexible and versatile to adapt to any new environment and work on any new technologies. Able to handle complex situations and time crunch schedules, creating more value for the company and for the client. Strong communication and analytical skills and ability to learn  migrate to different platforms, Applications and languages quickly. Good knowledge and skill of designing, analysis, testing and coding modules while structuring customized solutions to meet client’s specific needs.</p>
			</div>
			<div class="col-md-4 about-right">
				<ul>
					<h5>Awards</h5>
					<li><span class="glyphicon glyphicon-menu-right"></span> Certification in Java by Naresh. IT</li>
					<li><span class="glyphicon glyphicon-menu-right"></span> Certification in Ethical Hacking.</li>
					<li><span class="glyphicon glyphicon-menu-right"></span> Certification by Udemy.</li>
					<li><span class="glyphicon glyphicon-menu-right"></span> Winning the codewars challenge.</li>
					<li><span class="glyphicon glyphicon-menu-right"></span> Winner in several Coding Challenges.</li>
				</ul>
				<div class="clearfix"> </div>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!--//about-->

app/views/layouts/resume/_banner.html.erb
<div id="home" class="banner">
		<div class="banner-info">
			<div class="container">
				<div class="col-md-4 header-left">
					<img src="<%= asset_path 'avinash.jpg' %>" alt=""/>
				</div>
				<div class="col-md-8 header-right">
					<h2>Hello</h2>
					<h1>I'm Avinash Kumar</h1>
					<h6>Full Stack Developer</h6>
					<ul class="address">
						<li>
							<ul class="address-text">
								<li><b>D.O.B</b></li>
								<li>04-July-1991</li>
							</ul>
						</li>
						<li>
							<ul class="address-text">
								<li><b>PHONE </b></li>
								<li>+91 812 068 2298</li>
							</ul>
						</li>
						<li>
							<ul class="address-text">
								<li><b>ADDRESS </b></li>
								<li>Bailey Road, R.K Puram Patna </li>
							</ul>
						</li>
						<li>
							<ul class="address-text">
								<li><b>E-MAIL </b></li>
								<li><a href="mailto:avi4791@gmail.com"> avi4791@gmail.com</a></li>
							</ul>
						</li>
						<li>
							<ul class="address-text">
								<li><b>WEBSITE </b></li>
								<li><a href="http://avinashmehta.herokuapp.com">www.avinash.com</a></li>
							</ul>
						</li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>

app/views/layouts/resume/_contact.html.erb
	<div class="welcome contact" id="contact">
		<div class="container">
			<h3 class="title">Contact Us</h3>
			<div class="contact-row">
				<div class="col-md-6 contact-left">
					<iframe src="https://www.google.com/maps/@25.8243998,85.20376,8.92z"></iframe>
				</div>
				<div class="col-md-6 contact-right">
					<div class="address-left">
						<p>Bailey Road, R.K Puram Patna,<br> Patna,Bihar India</p>
					</div>
					<div class="address-right">
						<p>Call us :  +91 812 068 2298</p>
						<p>E-mail : <a href="mailto:avi4791@gmail.com">avi4791@gmail.com</a></p>
					</div>
					<div class="clearfix"></div>
					<div class="contact-form">
							<%=form_for Feedback.new, :url => home_feedback_path do |f|%> 
							<div class="field">
							    <%= f.label :name %><br>
							    <%= f.text_field :name , placeholder: "Name" ,required: true%>
							  </div>
							  <div class="field">
							    <%= f.label :contact %><br>
							    <%= f.text_field :contact,  placeholder: "Contact" ,required: true %>
							  </div>
							  <div class="field">
							    <%= f.label :email %><br>
							    <%= f.text_field :email,  placeholder: "Email" ,required: true%>
							  </div>
							  <div class="field">
							    <%= f.label :message %><br>
							    <%= f.text_area :message,  placeholder: "Message" ,required: true %>
							  </div>
							  <div class="actions">
							    <%= f.submit %>
							  </div>
								</form>
						<% end %>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>

app/views/layouts/resume/_education.html.erb
	<!--education-->
	<div id="education" class="education">
		<div class="container">
			<h3 class="title">Education</h3>
			<div class="work-info"> 
				<div class="col-md-6 work-left"> 
					<h4>Bachlore Of Engineering  2012 - 2016</h4>
				</div>
				<div class="col-md-6 work-right"> 
					<h5><span class="glyphicon glyphicon-education"> </span>Chhattisgarh Swami Vivekanand Technical University</h5>
					<p>Chhattisgarh Swami Vivekanand Technical University (CSVTU) was established by an act (No. 25 of 2004) of legislature passed by the Chhattisgarh State Govt. Assembly vide notification no. 639/21-A/Praroopan/04 dt 21st January 2005</p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="work-info"> 
				<div class="col-md-6 work-right work-right2"> 
					<h4>Senior School Certification - 2011</h4>
				</div>
				<div class="col-md-6 work-left work-left2"> 
					<h5>Central Board of Secondary Education <span class="glyphicon glyphicon-education"></span></h5>
					<p>The Central Board of Secondary Education (CBSE) is a national level board of education in India for public and private schools, controlled and managed by Union Government of India. CBSE has asked all schools affiliated to follow only NCERT curriculum.[2] There are approximately 19,316 schools in India and 211 schools in 25 foreign countries affiliated to the CBSE</p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="work-info"> 
				<div class="col-md-6 work-left"> 
					<h4> Secondary School - 2007 </h4>
				</div>
				<div class="col-md-6 work-right"> 
					<h5><span class="glyphicon glyphicon-education"></span> Kendriya Vidyalaya Danapur  </h5>
					<p>The Kendriya Vidyalayas Sangathan (lit. "central schools") is a system of central government schools in India that are instituted under the aegis of the Ministry of Human Resource Development (MHRD). It comprises over 1,193 schools in India (as of 1 November 2018) and three abroad. It is one of world's largest chains of schools.</p>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--//education-->

app/views/layouts/resume/_experience.html.erb
	<!--work-experience-->
	<div id="work" class="work">
		<div class="container">
			<h3 class="title">Work Experience</h3>
			<div class="work-info"> 
				<div class="col-md-6 work-left"> 
					<h4>2017 - 2018 </h4>
				</div>
				<div class="col-md-6 work-right"> 
					<h5><span class="glyphicon glyphicon-briefcase"><a href="http://complitech.us" target ="_blank"></span> Complitech Solution Pvt Ltd.</h5></a>
					<p>The short answer is we were there when it all began, creating some of world’s first mobile applications in early 2008. Mobile development has changed considerably since then, and we haven’t looked back.</p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="work-info"> 
				<div class="col-md-6 work-right work-right2"> 
					<h4>2016 - 2017 </h4>
				</div>
				<div class="col-md-6 work-left work-left2"><a href="http://irissbsp.com" target ="_blank">
					<h5> Iriss Electronic Travel Distribution Pvt Ltd. </a><span class="glyphicon glyphicon-briefcase"> </span></h5>
					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo </p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="work-info"> 
				<div class="col-md-6 work-left"> 
					<h4>2015 - 2016 </h4>
				</div>
				<div class="col-md-6 work-right"> 
					<h5><span class="glyphicon glyphicon-briefcase"> </span><a href="http://cplus.in" target ="_blank"> Computer Plus</h5></a>
					<p>Computer Plus is one place for all GIS Analysis & Mapping, GPS & DGPS Survey,Software,WEB & Mobile development work because meeting just your requirement is not enough, So for better result we dedicate our focus on Customer needs, Speedy delivery, Quality execution with affordable pricing . </p>
				</div>
				<div class="clearfix"> </div>
			</div>
<!-- 			<div class="work-info"> 
				<div class="col-md-6 work-right work-right2"> 
					<h4>2010 - 2012 </h4>
				</div>
				<div class="col-md-6 work-left work-left2"> 
					<h5> Company Name <span class="glyphicon glyphicon-briefcase"></span> </h5>
					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo </p>
				</div>
				<div class="clearfix"> </div>
			</div> -->
		</div>
	</div>
	<!--//work-experience-->

app/views/layouts/resume/_footer.html.erb
<div class="footer">
		<div class="container">
			<p>© 2018 My Resume. All rights reserved | Design by <a href="http://avinashmehta.herokuapp.com">Avinash Kumar</a></p>
		</div>
	</div>
	<!--//footer-->
	<!--smooth-scrolling-of-move-up-->
	<script src="../assets/move-top.js" type="text/javascript"></script>
	<script>
		$(document).ready(function() {
		
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
			};
			
			// $().UItoTop({ easingType: 'easeOutQuart' });
			
		});
	</script>

app/views/layouts/resume/_navigation.html.erb
	<div class="top-nav wow">
		<div class="container">
			<div class="navbar-header logo">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					Menu
				</button>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<div class="menu">
					<ul class="nav navbar">
						<li><a href="#about" class="scroll">About</a></li>
						<li><a href="#work" class="scroll">Experience</a></li>
						<li><a href="#education" class="scroll">Education</a></li>
						<li><a href="#skills" class="scroll">Skills</a></li>
						<li><a href="#projects" class="scroll">My Projects</a></li>
						<li><a href="#contact" class="scroll">Contact</a></li>
					</ul>
					<div class="clearfix"> </div>
				</div>
			</div>
		</div>
	</div>	

app/views/layouts/resume/_skills.html.erb
<div id="skills" class="skills">
		<div class="container">
			<h3 class="title">Skills</h3>
			<div class="skills-info">
				<div class="col-md-6 bar-grids">
					<h6> RUBY <span> 70% </span></h6>
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" style="width: 70%">
						</div>
					</div>
					<h6>RUBY ON RAILS <span> 70% </span></h6>
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" style="width: 70%">
						</div>
					</div>
					<h6>HTML/CSS<span>60% </span></h6>
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" style="width: 60%">
						</div>
					</div>
					<h6>PHOTOSHOP <span> 75% </span></h6>
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" style="width: 75%">
						</div>
					</div>
				</div>
				<div class="col-md-6 bar-grids">
					<h6> DESIGN <span> 60% </span></h6>
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" style="width: 60%">
						</div>
					</div>
					<h6>JAVA SCRIPT<span> 50% </span></h6>
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" style="width: 50%">
						</div>
					</div>
					<h6>JAVA <span>60% </span></h6>
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" style="width: 60%">
						</div>
					</div>
					<h6> DATABASE <span> 65% </span></h6>
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" style="width: 65%">
						</div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--//skills-->